import Link from 'http-link-header';
import { SearchResultsPaginationData } from '../search-results-page';
import { User } from '../user';
import { linkHeadersRaw } from './link-mocks';

export const searchResultsPaginationDataMock: SearchResultsPaginationData<User> = {
  paginationInfo: new Link(linkHeadersRaw),
  searchResults: {
    incomplete_results: false,
    items: [
      {
        login: 'morenoh149',
        id: 587438,
        node_id: 'MDQ6VXNlcjU4NzQzOA==',
        avatar_url: 'https://avatars.githubusercontent.com/u/587438?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/morenoh149',
        html_url: 'https://github.com/morenoh149',
        followers_url: 'https://api.github.com/users/morenoh149/followers',
        following_url: 'https://api.github.com/users/morenoh149/following{/other_user}',
        gists_url: 'https://api.github.com/users/morenoh149/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/morenoh149/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/morenoh149/subscriptions',
        organizations_url: 'https://api.github.com/users/morenoh149/orgs',
        repos_url: 'https://api.github.com/users/morenoh149/repos',
        events_url: 'https://api.github.com/users/morenoh149/events{/privacy}',
        received_events_url: 'https://api.github.com/users/morenoh149/received_events',
        type: 'User',
        site_admin: false,
        score: 1
      },
      {
        login: 'moredip',
        id: 65444,
        node_id: 'MDQ6VXNlcjY1NDQ0',
        avatar_url: 'https://avatars.githubusercontent.com/u/65444?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/moredip',
        html_url: 'https://github.com/moredip',
        followers_url: 'https://api.github.com/users/moredip/followers',
        following_url: 'https://api.github.com/users/moredip/following{/other_user}',
        gists_url: 'https://api.github.com/users/moredip/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/moredip/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/moredip/subscriptions',
        organizations_url: 'https://api.github.com/users/moredip/orgs',
        repos_url: 'https://api.github.com/users/moredip/repos',
        events_url: 'https://api.github.com/users/moredip/events{/privacy}',
        received_events_url: 'https://api.github.com/users/moredip/received_events',
        type: 'User',
        site_admin: false,
        score: 1
      },
      {
        login: 'moreal',
        id: 26626194,
        node_id: 'MDQ6VXNlcjI2NjI2MTk0',
        avatar_url: 'https://avatars.githubusercontent.com/u/26626194?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/moreal',
        html_url: 'https://github.com/moreal',
        followers_url: 'https://api.github.com/users/moreal/followers',
        following_url: 'https://api.github.com/users/moreal/following{/other_user}',
        gists_url: 'https://api.github.com/users/moreal/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/moreal/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/moreal/subscriptions',
        organizations_url: 'https://api.github.com/users/moreal/orgs',
        repos_url: 'https://api.github.com/users/moreal/repos',
        events_url: 'https://api.github.com/users/moreal/events{/privacy}',
        received_events_url: 'https://api.github.com/users/moreal/received_events',
        type: 'User',
        site_admin: false,
        score: 1
      },
      {
        login: 'MorenaNobre',
        id: 29803756,
        node_id: 'MDQ6VXNlcjI5ODAzNzU2',
        avatar_url: 'https://avatars.githubusercontent.com/u/29803756?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/MorenaNobre',
        html_url: 'https://github.com/MorenaNobre',
        followers_url: 'https://api.github.com/users/MorenaNobre/followers',
        following_url: 'https://api.github.com/users/MorenaNobre/following{/other_user}',
        gists_url: 'https://api.github.com/users/MorenaNobre/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/MorenaNobre/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/MorenaNobre/subscriptions',
        organizations_url: 'https://api.github.com/users/MorenaNobre/orgs',
        repos_url: 'https://api.github.com/users/MorenaNobre/repos',
        events_url: 'https://api.github.com/users/MorenaNobre/events{/privacy}',
        received_events_url: 'https://api.github.com/users/MorenaNobre/received_events',
        type: 'User',
        site_admin: false,
        score: 1
      },
      {
        login: 'Morendil',
        id: 216452,
        node_id: 'MDQ6VXNlcjIxNjQ1Mg==',
        avatar_url: 'https://avatars.githubusercontent.com/u/216452?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/Morendil',
        html_url: 'https://github.com/Morendil',
        followers_url: 'https://api.github.com/users/Morendil/followers',
        following_url: 'https://api.github.com/users/Morendil/following{/other_user}',
        gists_url: 'https://api.github.com/users/Morendil/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/Morendil/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/Morendil/subscriptions',
        organizations_url: 'https://api.github.com/users/Morendil/orgs',
        repos_url: 'https://api.github.com/users/Morendil/repos',
        events_url: 'https://api.github.com/users/Morendil/events{/privacy}',
        received_events_url: 'https://api.github.com/users/Morendil/received_events',
        type: 'User',
        site_admin: false,
        score: 1
      },
      {
        login: 'moretti',
        id: 1186409,
        node_id: 'MDQ6VXNlcjExODY0MDk=',
        avatar_url: 'https://avatars.githubusercontent.com/u/1186409?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/moretti',
        html_url: 'https://github.com/moretti',
        followers_url: 'https://api.github.com/users/moretti/followers',
        following_url: 'https://api.github.com/users/moretti/following{/other_user}',
        gists_url: 'https://api.github.com/users/moretti/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/moretti/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/moretti/subscriptions',
        organizations_url: 'https://api.github.com/users/moretti/orgs',
        repos_url: 'https://api.github.com/users/moretti/repos',
        events_url: 'https://api.github.com/users/moretti/events{/privacy}',
        received_events_url: 'https://api.github.com/users/moretti/received_events',
        type: 'User',
        site_admin: false,
        score: 1
      },
      {
        login: 'morethanreal',
        id: 1202776,
        node_id: 'MDQ6VXNlcjEyMDI3NzY=',
        avatar_url: 'https://avatars.githubusercontent.com/u/1202776?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/morethanreal',
        html_url: 'https://github.com/morethanreal',
        followers_url: 'https://api.github.com/users/morethanreal/followers',
        following_url: 'https://api.github.com/users/morethanreal/following{/other_user}',
        gists_url: 'https://api.github.com/users/morethanreal/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/morethanreal/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/morethanreal/subscriptions',
        organizations_url: 'https://api.github.com/users/morethanreal/orgs',
        repos_url: 'https://api.github.com/users/morethanreal/repos',
        events_url: 'https://api.github.com/users/morethanreal/events{/privacy}',
        received_events_url: 'https://api.github.com/users/morethanreal/received_events',
        type: 'User',
        site_admin: false,
        score: 1
      },
      {
        login: 'morecallan',
        id: 16550897,
        node_id: 'MDQ6VXNlcjE2NTUwODk3',
        avatar_url: 'https://avatars.githubusercontent.com/u/16550897?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/morecallan',
        html_url: 'https://github.com/morecallan',
        followers_url: 'https://api.github.com/users/morecallan/followers',
        following_url: 'https://api.github.com/users/morecallan/following{/other_user}',
        gists_url: 'https://api.github.com/users/morecallan/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/morecallan/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/morecallan/subscriptions',
        organizations_url: 'https://api.github.com/users/morecallan/orgs',
        repos_url: 'https://api.github.com/users/morecallan/repos',
        events_url: 'https://api.github.com/users/morecallan/events{/privacy}',
        received_events_url: 'https://api.github.com/users/morecallan/received_events',
        type: 'User',
        site_admin: false,
        score: 1
      },
      {
        login: 'morelli690',
        id: 17299358,
        node_id: 'MDQ6VXNlcjE3Mjk5MzU4',
        avatar_url: 'https://avatars.githubusercontent.com/u/17299358?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/morelli690',
        html_url: 'https://github.com/morelli690',
        followers_url: 'https://api.github.com/users/morelli690/followers',
        following_url: 'https://api.github.com/users/morelli690/following{/other_user}',
        gists_url: 'https://api.github.com/users/morelli690/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/morelli690/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/morelli690/subscriptions',
        organizations_url: 'https://api.github.com/users/morelli690/orgs',
        repos_url: 'https://api.github.com/users/morelli690/repos',
        events_url: 'https://api.github.com/users/morelli690/events{/privacy}',
        received_events_url: 'https://api.github.com/users/morelli690/received_events',
        type: 'User',
        site_admin: false,
        score: 1
      }
    ],
    total_count: 112
  }
};

export const searchResultsPaginationDataMock2: SearchResultsPaginationData<User> = {
  paginationInfo: new Link(linkHeadersRaw),
  searchResults: {
    incomplete_results: false,
    items: [
      {
        login: 'morenoh149',
        id: 587438,
        node_id: 'MDQ6VXNlcjU4NzQzOA==',
        avatar_url: 'https://avatars.githubusercontent.com/u/587438?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/morenoh149',
        html_url: 'https://github.com/morenoh149',
        followers_url: 'https://api.github.com/users/morenoh149/followers',
        following_url: 'https://api.github.com/users/morenoh149/following{/other_user}',
        gists_url: 'https://api.github.com/users/morenoh149/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/morenoh149/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/morenoh149/subscriptions',
        organizations_url: 'https://api.github.com/users/morenoh149/orgs',
        repos_url: 'https://api.github.com/users/morenoh149/repos',
        events_url: 'https://api.github.com/users/morenoh149/events{/privacy}',
        received_events_url: 'https://api.github.com/users/morenoh149/received_events',
        type: 'User',
        site_admin: false,
        score: 1
      },
      {
        login: 'moredip',
        id: 65444,
        node_id: 'MDQ6VXNlcjY1NDQ0',
        avatar_url: 'https://avatars.githubusercontent.com/u/65444?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/moredip',
        html_url: 'https://github.com/moredip',
        followers_url: 'https://api.github.com/users/moredip/followers',
        following_url: 'https://api.github.com/users/moredip/following{/other_user}',
        gists_url: 'https://api.github.com/users/moredip/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/moredip/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/moredip/subscriptions',
        organizations_url: 'https://api.github.com/users/moredip/orgs',
        repos_url: 'https://api.github.com/users/moredip/repos',
        events_url: 'https://api.github.com/users/moredip/events{/privacy}',
        received_events_url: 'https://api.github.com/users/moredip/received_events',
        type: 'User',
        site_admin: false,
        score: 1
      },
      {
        login: 'moreal',
        id: 26626194,
        node_id: 'MDQ6VXNlcjI2NjI2MTk0',
        avatar_url: 'https://avatars.githubusercontent.com/u/26626194?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/moreal',
        html_url: 'https://github.com/moreal',
        followers_url: 'https://api.github.com/users/moreal/followers',
        following_url: 'https://api.github.com/users/moreal/following{/other_user}',
        gists_url: 'https://api.github.com/users/moreal/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/moreal/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/moreal/subscriptions',
        organizations_url: 'https://api.github.com/users/moreal/orgs',
        repos_url: 'https://api.github.com/users/moreal/repos',
        events_url: 'https://api.github.com/users/moreal/events{/privacy}',
        received_events_url: 'https://api.github.com/users/moreal/received_events',
        type: 'User',
        site_admin: false,
        score: 1
      },
      {
        login: 'MorenaNobre',
        id: 29803756,
        node_id: 'MDQ6VXNlcjI5ODAzNzU2',
        avatar_url: 'https://avatars.githubusercontent.com/u/29803756?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/MorenaNobre',
        html_url: 'https://github.com/MorenaNobre',
        followers_url: 'https://api.github.com/users/MorenaNobre/followers',
        following_url: 'https://api.github.com/users/MorenaNobre/following{/other_user}',
        gists_url: 'https://api.github.com/users/MorenaNobre/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/MorenaNobre/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/MorenaNobre/subscriptions',
        organizations_url: 'https://api.github.com/users/MorenaNobre/orgs',
        repos_url: 'https://api.github.com/users/MorenaNobre/repos',
        events_url: 'https://api.github.com/users/MorenaNobre/events{/privacy}',
        received_events_url: 'https://api.github.com/users/MorenaNobre/received_events',
        type: 'User',
        site_admin: false,
        score: 1
      },
      {
        login: 'Morendil',
        id: 216452,
        node_id: 'MDQ6VXNlcjIxNjQ1Mg==',
        avatar_url: 'https://avatars.githubusercontent.com/u/216452?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/Morendil',
        html_url: 'https://github.com/Morendil',
        followers_url: 'https://api.github.com/users/Morendil/followers',
        following_url: 'https://api.github.com/users/Morendil/following{/other_user}',
        gists_url: 'https://api.github.com/users/Morendil/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/Morendil/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/Morendil/subscriptions',
        organizations_url: 'https://api.github.com/users/Morendil/orgs',
        repos_url: 'https://api.github.com/users/Morendil/repos',
        events_url: 'https://api.github.com/users/Morendil/events{/privacy}',
        received_events_url: 'https://api.github.com/users/Morendil/received_events',
        type: 'User',
        site_admin: false,
        score: 1
      },
      {
        login: 'moretti',
        id: 1186409,
        node_id: 'MDQ6VXNlcjExODY0MDk=',
        avatar_url: 'https://avatars.githubusercontent.com/u/1186409?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/moretti',
        html_url: 'https://github.com/moretti',
        followers_url: 'https://api.github.com/users/moretti/followers',
        following_url: 'https://api.github.com/users/moretti/following{/other_user}',
        gists_url: 'https://api.github.com/users/moretti/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/moretti/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/moretti/subscriptions',
        organizations_url: 'https://api.github.com/users/moretti/orgs',
        repos_url: 'https://api.github.com/users/moretti/repos',
        events_url: 'https://api.github.com/users/moretti/events{/privacy}',
        received_events_url: 'https://api.github.com/users/moretti/received_events',
        type: 'User',
        site_admin: false,
        score: 1
      },
      {
        login: 'morethanreal',
        id: 1202776,
        node_id: 'MDQ6VXNlcjEyMDI3NzY=',
        avatar_url: 'https://avatars.githubusercontent.com/u/1202776?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/morethanreal',
        html_url: 'https://github.com/morethanreal',
        followers_url: 'https://api.github.com/users/morethanreal/followers',
        following_url: 'https://api.github.com/users/morethanreal/following{/other_user}',
        gists_url: 'https://api.github.com/users/morethanreal/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/morethanreal/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/morethanreal/subscriptions',
        organizations_url: 'https://api.github.com/users/morethanreal/orgs',
        repos_url: 'https://api.github.com/users/morethanreal/repos',
        events_url: 'https://api.github.com/users/morethanreal/events{/privacy}',
        received_events_url: 'https://api.github.com/users/morethanreal/received_events',
        type: 'User',
        site_admin: false,
        score: 1
      },
      {
        login: 'morecallan',
        id: 16550897,
        node_id: 'MDQ6VXNlcjE2NTUwODk3',
        avatar_url: 'https://avatars.githubusercontent.com/u/16550897?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/morecallan',
        html_url: 'https://github.com/morecallan',
        followers_url: 'https://api.github.com/users/morecallan/followers',
        following_url: 'https://api.github.com/users/morecallan/following{/other_user}',
        gists_url: 'https://api.github.com/users/morecallan/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/morecallan/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/morecallan/subscriptions',
        organizations_url: 'https://api.github.com/users/morecallan/orgs',
        repos_url: 'https://api.github.com/users/morecallan/repos',
        events_url: 'https://api.github.com/users/morecallan/events{/privacy}',
        received_events_url: 'https://api.github.com/users/morecallan/received_events',
        type: 'User',
        site_admin: false,
        score: 1
      },
      {
        login: 'morelli690',
        id: 17299358,
        node_id: 'MDQ6VXNlcjE3Mjk5MzU4',
        avatar_url: 'https://avatars.githubusercontent.com/u/17299358?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/morelli690',
        html_url: 'https://github.com/morelli690',
        followers_url: 'https://api.github.com/users/morelli690/followers',
        following_url: 'https://api.github.com/users/morelli690/following{/other_user}',
        gists_url: 'https://api.github.com/users/morelli690/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/morelli690/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/morelli690/subscriptions',
        organizations_url: 'https://api.github.com/users/morelli690/orgs',
        repos_url: 'https://api.github.com/users/morelli690/repos',
        events_url: 'https://api.github.com/users/morelli690/events{/privacy}',
        received_events_url: 'https://api.github.com/users/morelli690/received_events',
        type: 'User',
        site_admin: false,
        score: 1
      }
    ],
    total_count: 112
  }
};
